[theme]
primaryColor = "#00BFFF"
backgroundColor = "#0b1120"
secondaryBackgroundColor = "#111d33"
textColor = "#e0e6ed"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
